### ISSUE TITLE
Make the main landing page responsive on mobile device

### ISSUE THREAD

**Issue by Sahad-09** [Sahad-09/Website-for-Hiure#2]
The page is in Home.jsx file, On mobile devices I want the image to be on top and texts to be on bottom of it.
Happy coding :)

**Comment by imbhaskarn** [comment]
@Sahad-09 I have made the changes but I cannot push changes to your repo

**Comment by Sahad-09** [comment]
> @Sahad-09 I have made the changes but I cannot push changes to your repo

Give it another try
